"""Primera migración

Revision ID: d225e79421c0
Revises: 
Create Date: 2025-03-10 18:15:19.476824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd225e79421c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('modelo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_id'), 'vehiculos', ['id'], unique=False)
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=True)
    op.create_table('reparaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('costo', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reparaciones_id'), 'reparaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reparaciones_id'), table_name='reparaciones')
    op.drop_table('reparaciones')
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_index(op.f('ix_vehiculos_id'), table_name='vehiculos')
    op.drop_table('vehiculos')
    # ### end Alembic commands ###
